export const ALL_PRODUCTS_LIST_REQUEST = "ALL_PRODUCTS_LIST_REQUEST";
export const ALL_PRODUCTS_LIST_SUCCESS = "ALL_PRODUCTS_LIST_SUCCESS";
export const ALL_PRODUCTS_LIST_FAIL = "ALL_PRODUCTS_LIST_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";